// SPDX-License-Identifier: ISC
//
// Typed SQL helpers — bridge between raw STDB SQL responses (positional arrays)
// and properly typed objects using the auto-generated module_bindings schemas.
//
// The module_bindings directory contains row schemas generated by `spacetime
// generate` from the Rust module. Each table schema (e.g. `page_table.ts`)
// exports a row definition via `__t.row({...})`.
//
// This module provides a `fromStdbRow` utility that introspects the module_binding
// schema at runtime to automatically convert positional row arrays from STDB's
// HTTP SQL API into properly typed JavaScript objects — without needing the
// manual `mappers.ts` functions.
//
// Usage:
//   import { fromStdbRow } from "./typed-sql";
//   import PageRowSchema from "../../module_bindings/page_table";
//   const rows = await sqlQuery("SELECT * FROM page");
//   const pages = rows.map(fromStdbRow(PageRowSchema));
//
// Long-term goal: Replace raw SQL + manual mappers with the SDK's typed
// subscription system (DbConnection + query builders).

import type { Infer as __Infer } from 'spacetimedb';

// ─── Row schema imports (auto-generated by `spacetime generate`) ───────
// These provide the canonical TypeScript types for each table.
import PageRowSchema from '../../module_bindings/page_table';
import CollectionRowSchema from '../../module_bindings/collection_table';
import UserRowSchema from '../../module_bindings/user_table';
import CommentRowSchema from '../../module_bindings/comment_table';
import CommentReactionRowSchema from '../../module_bindings/comment_reaction_table';
import PageTagRowSchema from '../../module_bindings/page_tag_table';
import AttachmentRowSchema from '../../module_bindings/attachment_table';
import CollectionMemberRowSchema from '../../module_bindings/collection_member_table';
import ShareLinkRowSchema from '../../module_bindings/share_link_table';
import ApiKeyRowSchema from '../../module_bindings/api_key_table';
import GroupRowSchema from '../../module_bindings/group_table';
import GroupMemberRowSchema from '../../module_bindings/group_member_table';
import CollectionGroupPermissionRowSchema from '../../module_bindings/collection_group_permission_table';
import PagePermissionRowSchema from '../../module_bindings/page_permission_table';
import WebhookRowSchema from '../../module_bindings/webhook_table';
import WebhookEventRowSchema from '../../module_bindings/webhook_event_table';
import OidcProviderRowSchema from '../../module_bindings/oidc_provider_table';
import SamlProviderRowSchema from '../../module_bindings/saml_provider_table';
import AppSettingRowSchema from '../../module_bindings/app_setting_table';
import ScimProviderRowSchema from '../../module_bindings/scim_provider_table';
import ScimEventRowSchema from '../../module_bindings/scim_event_table';
import InvitationRowSchema from '../../module_bindings/invitation_table';
import CollectionSortRuleRowSchema from '../../module_bindings/collection_sort_rule_table';
import LdapProviderRowSchema from '../../module_bindings/ldap_provider_table';
import LdapUserRowSchema from '../../module_bindings/ldap_user_table';
import WatchRowSchema from '../../module_bindings/watch_table';
import NotificationRowSchema from '../../module_bindings/notification_table';
import CollabSessionRowSchema from '../../module_bindings/collab_session_table';
import CollabUpdateRowSchema from '../../module_bindings/collab_update_table';
import PasskeyCredentialRowSchema from '../../module_bindings/passkey_credential_table';
import PasskeyChallengeRowSchema from '../../module_bindings/passkey_challenge_table';
import MfaMethodRowSchema from '../../module_bindings/mfa_method_table';
import MfaBackupCodeRowSchema from '../../module_bindings/mfa_backup_code_table';
import AiConfigRowSchema from '../../module_bindings/ai_config_table';
import AiChatSessionRowSchema from '../../module_bindings/ai_chat_session_table';
import AiChatMessageRowSchema from '../../module_bindings/ai_chat_message_table';
import DbBaseRowSchema from '../../module_bindings/db_base_table';
import DbColumnRowSchema from '../../module_bindings/db_column_table';
import DbRowRowSchema from '../../module_bindings/db_row_table';
import DbCellRowSchema from '../../module_bindings/db_cell_table';
import SyncedBlockRowSchema from '../../module_bindings/synced_block_table';
import SyncedBlockRefRowSchema from '../../module_bindings/synced_block_ref_table';
import AuditEventRowSchema from '../../module_bindings/audit_event_table';
import OauthProviderRowSchema from '../../module_bindings/oauth_provider_table';
import OauthUserRowSchema from '../../module_bindings/oauth_user_table';
import PageRevisionRowSchema from '../../module_bindings/page_revision_table';
import FavoriteRowSchema from '../../module_bindings/favorite_table';

// ─── Canonical Row Types (derived from module_bindings schemas) ────────
// These are the *single source of truth* for row shapes.
// The manual interfaces in `types.ts` should be replaced by these over time.

export type StdbPage = __Infer<typeof PageRowSchema>;
export type StdbCollection = __Infer<typeof CollectionRowSchema>;
export type StdbUser = __Infer<typeof UserRowSchema>;
export type StdbPageRevision = __Infer<typeof PageRevisionRowSchema>;
export type StdbComment = __Infer<typeof CommentRowSchema>;
export type StdbCommentReaction = __Infer<typeof CommentReactionRowSchema>;
export type StdbPageTag = __Infer<typeof PageTagRowSchema>;
export type StdbAttachment = __Infer<typeof AttachmentRowSchema>;
export type StdbCollectionMember = __Infer<typeof CollectionMemberRowSchema>;
export type StdbShareLink = __Infer<typeof ShareLinkRowSchema>;
export type StdbApiKey = __Infer<typeof ApiKeyRowSchema>;
export type StdbGroup = __Infer<typeof GroupRowSchema>;
export type StdbGroupMember = __Infer<typeof GroupMemberRowSchema>;
export type StdbCollectionGroupPermission = __Infer<typeof CollectionGroupPermissionRowSchema>;
export type StdbPagePermission = __Infer<typeof PagePermissionRowSchema>;
export type StdbWebhook = __Infer<typeof WebhookRowSchema>;
export type StdbWebhookEvent = __Infer<typeof WebhookEventRowSchema>;
export type StdbOidcProvider = __Infer<typeof OidcProviderRowSchema>;
export type StdbSamlProvider = __Infer<typeof SamlProviderRowSchema>;
export type StdbAppSetting = __Infer<typeof AppSettingRowSchema>;
export type StdbScimProvider = __Infer<typeof ScimProviderRowSchema>;
export type StdbScimEvent = __Infer<typeof ScimEventRowSchema>;
export type StdbInvitation = __Infer<typeof InvitationRowSchema>;
export type StdbCollectionSortRule = __Infer<typeof CollectionSortRuleRowSchema>;
export type StdbLdapProvider = __Infer<typeof LdapProviderRowSchema>;
export type StdbLdapUser = __Infer<typeof LdapUserRowSchema>;
export type StdbWatch = __Infer<typeof WatchRowSchema>;
export type StdbNotification = __Infer<typeof NotificationRowSchema>;
export type StdbCollabSession = __Infer<typeof CollabSessionRowSchema>;
export type StdbCollabUpdate = __Infer<typeof CollabUpdateRowSchema>;
export type StdbPasskeyCredential = __Infer<typeof PasskeyCredentialRowSchema>;
export type StdbPasskeyChallenge = __Infer<typeof PasskeyChallengeRowSchema>;
export type StdbMfaMethod = __Infer<typeof MfaMethodRowSchema>;
export type StdbMfaBackupCode = __Infer<typeof MfaBackupCodeRowSchema>;
export type StdbAiConfig = __Infer<typeof AiConfigRowSchema>;
export type StdbAiChatSession = __Infer<typeof AiChatSessionRowSchema>;
export type StdbAiChatMessage = __Infer<typeof AiChatMessageRowSchema>;
export type StdbDbBase = __Infer<typeof DbBaseRowSchema>;
export type StdbDbColumn = __Infer<typeof DbColumnRowSchema>;
export type StdbDbRow = __Infer<typeof DbRowRowSchema>;
export type StdbDbCell = __Infer<typeof DbCellRowSchema>;
export type StdbSyncedBlock = __Infer<typeof SyncedBlockRowSchema>;
export type StdbSyncedBlockRef = __Infer<typeof SyncedBlockRefRowSchema>;
export type StdbAuditEvent = __Infer<typeof AuditEventRowSchema>;
export type StdbOauthProvider = __Infer<typeof OauthProviderRowSchema>;
export type StdbOauthUser = __Infer<typeof OauthUserRowSchema>;
export type StdbFavorite = __Infer<typeof FavoriteRowSchema>;

// ─── Internal: element descriptor cache ────────────────────────────────
// Each schema's field order is resolved once (lazily) and cached.

type FieldDescriptor = {
  name: string;
  tag: string;
  coerce: (v: unknown) => unknown;
};

const elementCache = new WeakMap<object, FieldDescriptor[]>();

function getElements(schema: object): FieldDescriptor[] {
  const cached = elementCache.get(schema);
  if (cached) return cached;
  const s = schema as Record<string, unknown>;
  const elements = ((s.algebraicType as Record<string, unknown>)?.value as Record<string, unknown>)
    ?.elements as Array<Record<string, unknown>> | undefined;
  if (!Array.isArray(elements)) {
    throw new Error('fromStdbRow: schema does not expose algebraicType.value.elements');
  }
  const rowDef = s.row as Record<string, unknown> | undefined;
  const descs: FieldDescriptor[] = elements.map((el) => {
    const jsName = el.name as string;
    // Use the DB column name (from columnMetadata.name) if available,
    // otherwise fall back to the JS field name. This produces snake_case
    // keys matching the existing types.ts interfaces.
    const colMeta = rowDef?.[jsName] as Record<string, unknown> | undefined;
    const dbName =
      ((colMeta?.columnMetadata as Record<string, unknown> | undefined)?.name as string) ?? jsName;
    const tag = (el.algebraicType as Record<string, unknown>)?.tag as string;
    let coerce: (v: unknown) => unknown;
    switch (tag) {
      case 'String':
        coerce = (v: unknown) => (v ?? '') as string;
        break;
      case 'Bool':
        coerce = (v: unknown) => Boolean(v);
        break;
      case 'U32':
      case 'U64':
      case 'I32':
      case 'I64':
      case 'F32':
      case 'F64':
        coerce = (v: unknown) => Number(v) || 0;
        break;
      default:
        coerce = (v: unknown) => v as unknown;
        break; // arrays, tables, etc.
    }
    return { name: dbName, tag, coerce };
  });
  elementCache.set(schema, descs);
  return descs;
}

// ─── fromStdbRow ───────────────────────────────────────────────────────
// Converts a positional row array from STDB's HTTP SQL API into a typed
// object using the auto-generated module_binding row schema.
//
// The schema's `algebraicType.value.elements` array defines field order,
// which matches `SELECT *` column order from STDB.
//
// Usage:
//   const rows = await sqlQuery("SELECT * FROM page");
//   const pages = rows.map(fromStdbRow(PageRowSchema));
//   // pages: StdbPage[] (camelCase fields matching module_bindings)

export function fromStdbRow<T>(schema: object & { __isRowSchema?: never }): (row: unknown[]) => T {
  const fields = getElements(schema);
  return (row: unknown[]): T => {
    const obj: Record<string, unknown> = {};
    const len = Math.min(fields.length, row.length);
    for (let i = 0; i < len; i++) {
      obj[fields[i].name] = fields[i].coerce(row[i]);
    }
    return obj as T;
  };
}
