// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  pageId: __t.string().name('page_id'),
  requesterId: __t.string().name('requester_id'),
  reason: __t.string(),
  status: __t.string(),
  respondedBy: __t.string().name('responded_by'),
  respondedAt: __t.u64().name('responded_at'),
  createdAt: __t.u64().name('created_at'),
});
