// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  providerType: __t.string(),
  authorizeUrl: __t.string(),
  tokenUrl: __t.string(),
  userinfoUrl: __t.string(),
  scope: __t.string(),
  clientId: __t.string(),
  clientSecret: __t.string(),
  icon: __t.string(),
  autoRegister: __t.bool(),
  defaultRole: __t.string(),
  createdBy: __t.string(),
};
