// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  host: __t.string(),
  port: __t.u16(),
  isSecure: __t.bool(),
  bindDn: __t.string(),
  bindPassword: __t.string(),
  baseDn: __t.string(),
  userFilter: __t.string(),
  usernameAttribute: __t.string(),
  emailAttribute: __t.string(),
  nameAttribute: __t.string(),
  defaultRole: __t.string(),
  autoRegister: __t.bool(),
  createdBy: __t.string(),
};
