// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pageId: __t.string().name("page_id"),
  filename: __t.string(),
  mimeType: __t.string().name("mime_type"),
  sizeBytes: __t.u64().name("size_bytes"),
  storageKey: __t.string().name("storage_key"),
  uploadedBy: __t.string().name("uploaded_by"),
  createdAt: __t.u64().name("created_at"),
});
