// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  eventType: __t.string().name("event_type"),
  actorId: __t.string().name("actor_id"),
  targetId: __t.string().name("target_id"),
  targetName: __t.string().name("target_name"),
  metadata: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
