// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  slug: __t.string(),
  description: __t.string(),
  parentId: __t.string().name('parent_id'),
  icon: __t.string(),
  color: __t.string(),
  sortOrder: __t.u32().name('sort_order'),
  createdBy: __t.string().name('created_by'),
  createdAt: __t.u64().name('created_at'),
  updatedAt: __t.u64().name('updated_at'),
});
