// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  email: __t.string(),
  invitedBy: __t.string(),
  role: __t.string(),
  pageIds: __t.string(),
  collectionIds: __t.string(),
  token: __t.string(),
  message: __t.string(),
  expiresDays: __t.u32(),
};
