// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  baseId: __t.string().name('base_id'),
  name: __t.string(),
  fieldType: __t.string().name('field_type'),
  options: __t.string(),
  sortOrder: __t.u32().name('sort_order'),
  createdAt: __t.u64().name('created_at'),
  updatedAt: __t.u64().name('updated_at'),
});
