// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  slug: __t.string(),
  host: __t.string(),
  port: __t.u16(),
  isSecure: __t.bool().name("is_secure"),
  bindDn: __t.string().name("bind_dn"),
  bindPassword: __t.string().name("bind_password"),
  baseDn: __t.string().name("base_dn"),
  userFilter: __t.string().name("user_filter"),
  usernameAttribute: __t.string().name("username_attribute"),
  emailAttribute: __t.string().name("email_attribute"),
  nameAttribute: __t.string().name("name_attribute"),
  defaultRole: __t.string().name("default_role"),
  autoRegister: __t.bool().name("auto_register"),
  isActive: __t.bool().name("is_active"),
  createdBy: __t.string().name("created_by"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
