// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default {
  id: __t.string(),
  userId: __t.string(),
  providerId: __t.string(),
  externalId: __t.string(),
  externalUsername: __t.string(),
  externalEmail: __t.string(),
  accessToken: __t.string(),
  refreshToken: __t.string(),
  tokenExpiresAt: __t.u64(),
};
