// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  eventType: __t.string().name("event_type"),
  targetId: __t.string().name("target_id"),
  title: __t.string(),
  message: __t.string(),
  actorId: __t.string().name("actor_id"),
  icon: __t.string(),
  isRead: __t.bool().name("is_read"),
  createdAt: __t.u64().name("created_at"),
});
