// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  providerId: __t.string().name("provider_id"),
  externalId: __t.string().name("external_id"),
  externalUsername: __t.string().name("external_username"),
  externalEmail: __t.string().name("external_email"),
  accessToken: __t.string().name("access_token"),
  refreshToken: __t.string().name("refresh_token"),
  tokenExpiresAt: __t.u64().name("token_expires_at"),
  lastSyncedAt: __t.u64().name("last_synced_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
