// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  slug: __t.string(),
  providerType: __t.string().name('provider_type'),
  authorizeUrl: __t.string().name('authorize_url'),
  tokenUrl: __t.string().name('token_url'),
  userinfoUrl: __t.string().name('userinfo_url'),
  scope: __t.string(),
  clientId: __t.string().name('client_id'),
  clientSecret: __t.string().name('client_secret'),
  icon: __t.string(),
  isActive: __t.bool().name('is_active'),
  autoRegister: __t.bool().name('auto_register'),
  defaultRole: __t.string().name('default_role'),
  createdBy: __t.string().name('created_by'),
  createdAt: __t.u64().name('created_at'),
  updatedAt: __t.u64().name('updated_at'),
});
