// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  title: __t.string(),
  slug: __t.string(),
  content: __t.string(),
  textContent: __t.string().name('text_content'),
  collectionId: __t.string().name('collection_id'),
  parentPageId: __t.string().name('parent_page_id'),
  status: __t.string(),
  icon: __t.string(),
  color: __t.string(),
  fullWidth: __t.bool().name('full_width'),
  isPinned: __t.bool().name('is_pinned'),
  isTemplate: __t.bool().name('is_template'),
  templateId: __t.string().name('template_id'),
  sortOrder: __t.u32().name('sort_order'),
  createdBy: __t.string().name('created_by'),
  updatedBy: __t.string().name('updated_by'),
  createdAt: __t.u64().name('created_at'),
  updatedAt: __t.u64().name('updated_at'),
  publishedAt: __t.u64().name('published_at'),
  deletedAt: __t.u64().name('deleted_at'),
  direction: __t.string(),
});
