// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  pageId: __t.string().name('page_id'),
  title: __t.string(),
  content: __t.string(),
  editedBy: __t.string().name('edited_by'),
  createdAt: __t.u64().name('created_at'),
  revisionNumber: __t.u32().name('revision_number'),
});
