// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  challenge: __t.string().primaryKey(),
  userHandle: __t.string().name('user_handle'),
  purpose: __t.string(),
  createdAt: __t.u64().name('created_at'),
  expiresAt: __t.u64().name('expires_at'),
});
