// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  providerId: __t.string().name('provider_id'),
  resourceType: __t.string().name('resource_type'),
  operation: __t.string(),
  externalId: __t.string().name('external_id'),
  localId: __t.string().name('local_id'),
  status: __t.string(),
  detail: __t.string(),
  createdAt: __t.u64().name('created_at'),
});
