// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default {
  email: __t.string(),
  name: __t.string(),
  externalId: __t.string(),
  providerId: __t.string(),
  defaultRole: __t.string(),
  autoRegister: __t.bool(),
};
