// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccessRequest = __t.object("AccessRequest", {
  id: __t.string(),
  pageId: __t.string(),
  requesterId: __t.string(),
  reason: __t.string(),
  status: __t.string(),
  respondedBy: __t.string(),
  respondedAt: __t.u64(),
  createdAt: __t.u64(),
});
export type AccessRequest = __Infer<typeof AccessRequest>;

export const AiChatMessage = __t.object("AiChatMessage", {
  id: __t.string(),
  sessionId: __t.string(),
  role: __t.string(),
  content: __t.string(),
  createdAt: __t.u64(),
});
export type AiChatMessage = __Infer<typeof AiChatMessage>;

export const AiChatSession = __t.object("AiChatSession", {
  id: __t.string(),
  userId: __t.string(),
  title: __t.string(),
  pageContextId: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type AiChatSession = __Infer<typeof AiChatSession>;

export const AiConfig = __t.object("AiConfig", {
  key: __t.string(),
  value: __t.string(),
  updatedAt: __t.u64(),
});
export type AiConfig = __Infer<typeof AiConfig>;

export const ApiKey = __t.object("ApiKey", {
  id: __t.string(),
  userId: __t.string(),
  name: __t.string(),
  keyHash: __t.string(),
  keyPrefix: __t.string(),
  lastUsedAt: __t.u64(),
  createdAt: __t.u64(),
  expiresAt: __t.u64(),
  isRevoked: __t.bool(),
});
export type ApiKey = __Infer<typeof ApiKey>;

export const AppSetting = __t.object("AppSetting", {
  key: __t.string(),
  value: __t.string(),
  updatedAt: __t.u64(),
});
export type AppSetting = __Infer<typeof AppSetting>;

export const Attachment = __t.object("Attachment", {
  id: __t.string(),
  pageId: __t.string(),
  filename: __t.string(),
  mimeType: __t.string(),
  sizeBytes: __t.u64(),
  storageKey: __t.string(),
  uploadedBy: __t.string(),
  createdAt: __t.u64(),
});
export type Attachment = __Infer<typeof Attachment>;

export const AuditEvent = __t.object("AuditEvent", {
  id: __t.string(),
  eventType: __t.string(),
  actorId: __t.string(),
  targetId: __t.string(),
  targetName: __t.string(),
  metadata: __t.string(),
  createdAt: __t.u64(),
});
export type AuditEvent = __Infer<typeof AuditEvent>;

export const CollabSession = __t.object("CollabSession", {
  id: __t.string(),
  pageId: __t.string(),
  userId: __t.string(),
  userName: __t.string(),
  color: __t.string(),
  cursorPosition: __t.string(),
  lastSeenAt: __t.u64(),
  joinedAt: __t.u64(),
});
export type CollabSession = __Infer<typeof CollabSession>;

export const CollabUpdate = __t.object("CollabUpdate", {
  id: __t.string(),
  pageId: __t.string(),
  updateData: __t.string(),
  userId: __t.string(),
  createdAt: __t.u64(),
});
export type CollabUpdate = __Infer<typeof CollabUpdate>;

export const Collection = __t.object("Collection", {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  description: __t.string(),
  parentId: __t.string(),
  icon: __t.string(),
  color: __t.string(),
  sortOrder: __t.u32(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Collection = __Infer<typeof Collection>;

export const CollectionGroupPermission = __t.object("CollectionGroupPermission", {
  id: __t.string(),
  collectionId: __t.string(),
  groupId: __t.string(),
  role: __t.string(),
  createdAt: __t.u64(),
});
export type CollectionGroupPermission = __Infer<typeof CollectionGroupPermission>;

export const CollectionMember = __t.object("CollectionMember", {
  id: __t.string(),
  collectionId: __t.string(),
  userId: __t.string(),
  role: __t.string(),
  addedBy: __t.string(),
  createdAt: __t.u64(),
});
export type CollectionMember = __Infer<typeof CollectionMember>;

export const CollectionSortRule = __t.object("CollectionSortRule", {
  collectionId: __t.string(),
  sortField: __t.string(),
  sortDirection: __t.string(),
  autoApply: __t.bool(),
  updatedBy: __t.string(),
  updatedAt: __t.u64(),
});
export type CollectionSortRule = __Infer<typeof CollectionSortRule>;

export const Comment = __t.object("Comment", {
  id: __t.string(),
  pageId: __t.string(),
  parentCommentId: __t.string(),
  userId: __t.string(),
  body: __t.string(),
  textAnchor: __t.string(),
  isResolved: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Comment = __Infer<typeof Comment>;

export const CommentReaction = __t.object("CommentReaction", {
  id: __t.string(),
  commentId: __t.string(),
  userId: __t.string(),
  emoji: __t.string(),
  createdAt: __t.u64(),
});
export type CommentReaction = __Infer<typeof CommentReaction>;

export const DbBase = __t.object("DbBase", {
  id: __t.string(),
  pageId: __t.string(),
  title: __t.string(),
  viewType: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type DbBase = __Infer<typeof DbBase>;

export const DbCell = __t.object("DbCell", {
  id: __t.string(),
  rowId: __t.string(),
  columnId: __t.string(),
  value: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type DbCell = __Infer<typeof DbCell>;

export const DbColumn = __t.object("DbColumn", {
  id: __t.string(),
  baseId: __t.string(),
  name: __t.string(),
  fieldType: __t.string(),
  options: __t.string(),
  sortOrder: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type DbColumn = __Infer<typeof DbColumn>;

export const DbRow = __t.object("DbRow", {
  id: __t.string(),
  baseId: __t.string(),
  sortOrder: __t.u32(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type DbRow = __Infer<typeof DbRow>;

export const Favorite = __t.object("Favorite", {
  id: __t.string(),
  userId: __t.string(),
  pageId: __t.string(),
  createdAt: __t.u64(),
});
export type Favorite = __Infer<typeof Favorite>;

export const Group = __t.object("Group", {
  id: __t.string(),
  name: __t.string(),
  description: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Group = __Infer<typeof Group>;

export const GroupMember = __t.object("GroupMember", {
  id: __t.string(),
  groupId: __t.string(),
  userId: __t.string(),
  role: __t.string(),
  addedBy: __t.string(),
  createdAt: __t.u64(),
});
export type GroupMember = __Infer<typeof GroupMember>;

export const Invitation = __t.object("Invitation", {
  id: __t.string(),
  email: __t.string(),
  invitedBy: __t.string(),
  role: __t.string(),
  pageIds: __t.string(),
  collectionIds: __t.string(),
  token: __t.string(),
  status: __t.string(),
  message: __t.string(),
  expiresAt: __t.u64(),
  viewCount: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Invitation = __Infer<typeof Invitation>;

export const LdapProvider = __t.object("LdapProvider", {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  host: __t.string(),
  port: __t.u16(),
  isSecure: __t.bool(),
  bindDn: __t.string(),
  bindPassword: __t.string(),
  baseDn: __t.string(),
  userFilter: __t.string(),
  usernameAttribute: __t.string(),
  emailAttribute: __t.string(),
  nameAttribute: __t.string(),
  defaultRole: __t.string(),
  autoRegister: __t.bool(),
  isActive: __t.bool(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type LdapProvider = __Infer<typeof LdapProvider>;

export const LdapUser = __t.object("LdapUser", {
  id: __t.string(),
  userId: __t.string(),
  ldapProviderId: __t.string(),
  dn: __t.string(),
  externalId: __t.string(),
  lastSyncedAt: __t.u64(),
  createdAt: __t.u64(),
});
export type LdapUser = __Infer<typeof LdapUser>;

export const MfaBackupCode = __t.object("MfaBackupCode", {
  id: __t.string(),
  userId: __t.string(),
  codeHash: __t.string(),
  isUsed: __t.bool(),
  createdAt: __t.u64(),
});
export type MfaBackupCode = __Infer<typeof MfaBackupCode>;

export const MfaMethod = __t.object("MfaMethod", {
  id: __t.string(),
  userId: __t.string(),
  methodType: __t.string(),
  totpSecret: __t.string(),
  isEnabled: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type MfaMethod = __Infer<typeof MfaMethod>;

export const Notification = __t.object("Notification", {
  id: __t.string(),
  userId: __t.string(),
  eventType: __t.string(),
  targetId: __t.string(),
  title: __t.string(),
  message: __t.string(),
  actorId: __t.string(),
  icon: __t.string(),
  isRead: __t.bool(),
  createdAt: __t.u64(),
});
export type Notification = __Infer<typeof Notification>;

export const OauthProvider = __t.object("OauthProvider", {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  providerType: __t.string(),
  authorizeUrl: __t.string(),
  tokenUrl: __t.string(),
  userinfoUrl: __t.string(),
  scope: __t.string(),
  clientId: __t.string(),
  clientSecret: __t.string(),
  icon: __t.string(),
  isActive: __t.bool(),
  autoRegister: __t.bool(),
  defaultRole: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type OauthProvider = __Infer<typeof OauthProvider>;

export const OauthUser = __t.object("OauthUser", {
  id: __t.string(),
  userId: __t.string(),
  providerId: __t.string(),
  externalId: __t.string(),
  externalUsername: __t.string(),
  externalEmail: __t.string(),
  accessToken: __t.string(),
  refreshToken: __t.string(),
  tokenExpiresAt: __t.u64(),
  lastSyncedAt: __t.u64(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type OauthUser = __Infer<typeof OauthUser>;

export const OidcProvider = __t.object("OidcProvider", {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  issuerUrl: __t.string(),
  clientId: __t.string(),
  clientSecret: __t.string(),
  scopes: __t.string(),
  isActive: __t.bool(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type OidcProvider = __Infer<typeof OidcProvider>;

export const Page = __t.object("Page", {
  id: __t.string(),
  title: __t.string(),
  slug: __t.string(),
  content: __t.string(),
  textContent: __t.string(),
  collectionId: __t.string(),
  parentPageId: __t.string(),
  status: __t.string(),
  icon: __t.string(),
  color: __t.string(),
  fullWidth: __t.bool(),
  isPinned: __t.bool(),
  isTemplate: __t.bool(),
  templateId: __t.string(),
  sortOrder: __t.u32(),
  createdBy: __t.string(),
  updatedBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  publishedAt: __t.u64(),
  deletedAt: __t.u64(),
  direction: __t.string(),
});
export type Page = __Infer<typeof Page>;

export const PagePermission = __t.object("PagePermission", {
  id: __t.string(),
  pageId: __t.string(),
  userId: __t.string(),
  groupId: __t.string(),
  role: __t.string(),
  createdAt: __t.u64(),
});
export type PagePermission = __Infer<typeof PagePermission>;

export const PageRevision = __t.object("PageRevision", {
  id: __t.string(),
  pageId: __t.string(),
  title: __t.string(),
  content: __t.string(),
  editedBy: __t.string(),
  createdAt: __t.u64(),
  revisionNumber: __t.u32(),
});
export type PageRevision = __Infer<typeof PageRevision>;

export const PageTag = __t.object("PageTag", {
  id: __t.string(),
  pageId: __t.string(),
  name: __t.string(),
  value: __t.string(),
});
export type PageTag = __Infer<typeof PageTag>;

export const PageView = __t.object("PageView", {
  id: __t.string(),
  pageId: __t.string(),
  userId: __t.string(),
  viewer: __t.string(),
  viewedAt: __t.u64(),
});
export type PageView = __Infer<typeof PageView>;

export const PasskeyChallenge = __t.object("PasskeyChallenge", {
  challenge: __t.string(),
  userHandle: __t.string(),
  purpose: __t.string(),
  createdAt: __t.u64(),
  expiresAt: __t.u64(),
});
export type PasskeyChallenge = __Infer<typeof PasskeyChallenge>;

export const PasskeyCredential = __t.object("PasskeyCredential", {
  id: __t.string(),
  userId: __t.string(),
  credentialId: __t.string(),
  publicKey: __t.string(),
  counter: __t.u64(),
  transports: __t.string(),
  deviceName: __t.string(),
  createdAt: __t.u64(),
  lastUsedAt: __t.u64(),
});
export type PasskeyCredential = __Infer<typeof PasskeyCredential>;

export const SamlProvider = __t.object("SamlProvider", {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  entityId: __t.string(),
  ssoUrl: __t.string(),
  certificate: __t.string(),
  nameIdFormat: __t.string(),
  attributeMapping: __t.string(),
  autoRegister: __t.bool(),
  isActive: __t.bool(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type SamlProvider = __Infer<typeof SamlProvider>;

export const ScimEvent = __t.object("ScimEvent", {
  id: __t.string(),
  providerId: __t.string(),
  resourceType: __t.string(),
  operation: __t.string(),
  externalId: __t.string(),
  localId: __t.string(),
  status: __t.string(),
  detail: __t.string(),
  createdAt: __t.u64(),
});
export type ScimEvent = __Infer<typeof ScimEvent>;

export const ScimProvider = __t.object("ScimProvider", {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  apiTokenHash: __t.string(),
  isActive: __t.bool(),
  defaultRole: __t.string(),
  autoRegister: __t.bool(),
  deprovisionBehavior: __t.string(),
  syncGroups: __t.bool(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ScimProvider = __Infer<typeof ScimProvider>;

export const SearchResult = __t.object("SearchResult", {
  id: __t.string(),
  searchToken: __t.string(),
  pageId: __t.string(),
  title: __t.string(),
  slug: __t.string(),
  excerpt: __t.string(),
  matchType: __t.string(),
  createdAt: __t.u64(),
});
export type SearchResult = __Infer<typeof SearchResult>;

export const ShareLink = __t.object("ShareLink", {
  id: __t.string(),
  pageId: __t.string(),
  token: __t.string(),
  passwordHash: __t.string(),
  createdBy: __t.string(),
  expiresAt: __t.u64(),
  createdAt: __t.u64(),
  visitCount: __t.u32(),
  brandTitle: __t.option(__t.string()),
  brandLogoUrl: __t.option(__t.string()),
});
export type ShareLink = __Infer<typeof ShareLink>;

export const SyncedBlock = __t.object("SyncedBlock", {
  id: __t.string(),
  title: __t.string(),
  content: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  updatedBy: __t.string(),
});
export type SyncedBlock = __Infer<typeof SyncedBlock>;

export const SyncedBlockRef = __t.object("SyncedBlockRef", {
  id: __t.string(),
  blockId: __t.string(),
  pageId: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
});
export type SyncedBlockRef = __Infer<typeof SyncedBlockRef>;

export const User = __t.object("User", {
  id: __t.string(),
  name: __t.string(),
  email: __t.string(),
  passwordHash: __t.string(),
  role: __t.string(),
  avatarUrl: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type User = __Infer<typeof User>;

export const Watch = __t.object("Watch", {
  id: __t.string(),
  userId: __t.string(),
  targetType: __t.string(),
  targetId: __t.string(),
  createdAt: __t.u64(),
});
export type Watch = __Infer<typeof Watch>;

export const Webhook = __t.object("Webhook", {
  id: __t.string(),
  name: __t.string(),
  url: __t.string(),
  events: __t.string(),
  isActive: __t.bool(),
  secret: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Webhook = __Infer<typeof Webhook>;

export const WebhookEvent = __t.object("WebhookEvent", {
  id: __t.string(),
  webhookId: __t.string(),
  eventType: __t.string(),
  pageId: __t.string(),
  payload: __t.string(),
  status: __t.string(),
  responseCode: __t.u32(),
  responseBody: __t.string(),
  createdAt: __t.u64(),
  sentAt: __t.u64(),
});
export type WebhookEvent = __Infer<typeof WebhookEvent>;

