// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default {
  id: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  entityId: __t.string(),
  ssoUrl: __t.string(),
  certificate: __t.string(),
  nameIdFormat: __t.string(),
  attributeMapping: __t.string(),
  autoRegister: __t.bool(),
  isActive: __t.bool(),
};
