// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  webhookId: __t.string().name('webhook_id'),
  eventType: __t.string().name('event_type'),
  pageId: __t.string().name('page_id'),
  payload: __t.string(),
  status: __t.string(),
  responseCode: __t.u32().name('response_code'),
  responseBody: __t.string().name('response_body'),
  createdAt: __t.u64().name('created_at'),
  sentAt: __t.u64().name('sent_at'),
});
